/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    Chatroom: typeof import('./src/components/chatroom/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElChatHeader: typeof import('element-plus/es')['ElChatHeader']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    NNavbar: typeof import('./src/components/nNavbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchbar: typeof import('./src/components/searchbar/index.vue')['default']
    Sidebar: typeof import('./src/components/sidebar/index.vue')['default']
    SidebarSearch: typeof import('./src/components/layout/SidebarSearch.vue')['default']
    SplitWrapper: typeof import('./src/components/layout/SplitWrapper.vue')['default']
    ThreadList: typeof import('./src/components/layout/ThreadList.vue')['default']
  }
}
